version: "3"
services:
# Selenium browsers

  selenium-chrome:
    image: selenium/standalone-chrome:4.1.3-20220427
    shm_size: 2gb
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - selenium-docker-grid-network
    container_name: selenium-chrome

  selenium-edge:
    image: selenium/standalone-edge:4.1.3-20220427
    shm_size: 2gb
    ports:
      - 4445:4444
      - 5901:5900
    networks:
      - selenium-docker-grid-network
    container_name: selenium-edge

  selenium-firefox:
    image: selenium/standalone-firefox:4.1.3-20220427
    shm_size: 2gb
    ports:
      - 4446:4444
      - 5902:5900
    networks:
      - selenium-docker-grid-network
    container_name: selenium-firefox

# Cucumber tests

  chrome:
    build: .
    environment:
      BROWSER: chrome
      HUB_URL: http://selenium-chrome:4444/wd/hub
    volumes:
      - .:/app
    depends_on:
      - selenium-chrome
    networks:
      - selenium-docker-grid-network

  edge:
    build: .
    environment:
      BROWSER: edge
      HUB_URL: http://selenium-edge:4444/wd/hub
    volumes:
      - .:/app
    depends_on:
      - selenium-edge
    networks:
      - selenium-docker-grid-network

  firefox:
    build: .
    environment:
      BROWSER: firefox
      HUB_URL: http://selenium-firefox:4444/wd/hub
    volumes:
      - .:/app
    depends_on:
      - selenium-firefox
    networks:
      - selenium-docker-grid-network

networks:
  selenium-docker-grid-network:
    driver: bridge
    name: selenium-docker-grid-network
